//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public int producto_id { get; set; }
        public string nombre { get; set; }
        public decimal precio { get; set; }
        public Nullable<int> categoria_id { get; set; }
    
        public virtual Categorias Categorias { get; set; }
    }
}
